routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'post' => 'PostController',
]);

Route::resources([
    'follow' => 'FollowController',
]);

Route::resources([
    'profile' => 'ProfileController',
]);

Route::middleware('auth', 'throttle:60,1')->group(function () {
    Route::resource('post_like', 'PostLikeController', ['only' => ['destroy', 'store']]);
    Route::resource('comment_like', 'CommentLikeController', ['only' => ['destroy', 'store']]);
});

Route::post('/comment/{post_id}', 'CommentController@store');
//Route::get('/{user_id}', 'ProfileController@profile');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Post extends Model
{
    protected $table = "posts";
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment', 'post_id');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'post_tag', 'post_id', 'tag_id');
    }

    public function likes()
    {
        return $this->hasMany('App\PostLike', 'post_id');
    }

    public function isCreatedBySelf()
    {
        if ($this->user_id == Auth::id()) {
            return true;
        } else {
            return false;
        }
    }

    public function isLiked()
    {
        if (PostLike::where('post_id', '=', $this->id)->where('user_id', '=', Auth::id())->exists()) {
            return true;
        } else {
            return false;
        }
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use App\PostTag;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use RealRashid\SweetAlert\Facades\Alert;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->only(['index', 'create', 'store', 'edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        $tags = Tag::limit(3)->get();
        $users = User::inRandomOrder()->limit(3)->get()->except(Auth::id());

        return view('post.index', compact('posts', 'tags', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post;
        $user = Auth::user();

        $post->caption = $request['caption'];
        $post->user_id = $user->id;

        $tags_arr = explode(',', $request['tags']);
        $tag_ids = [];
        foreach ($tags_arr as $tag_name) {
            $tag = Tag::firstOrCreate([
                'tag_name' => $tag_name
            ]);
            $tag_ids[] = $tag->id;
        }

        if ($request->hasFile('img_url')) {
            $file = $request->file('img_url');
            $extension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $extension;
            $file->move('uploads/post', $filename);
            $post->img_url = $filename;
        } else {
            /* return $request; */
            $post->img_url = '';
        }

        $post->save();
        $post->tags()->sync($tag_ids);

        Alert::success('Success', 'Post added');

        return redirect('/post');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        if ($post->user_id != Auth::id()) {
            return redirect('post');
        }

        $post_tags = PostTag::where('post_id', '=', $id)->get();
        $name_arr = [];
        foreach ($post_tags as $tags) {
            $temp_tags = Tag::find($tags->tag_id);
            $name_arr[] = $temp_tags->tag_name;
        }

        $tag_name = implode(',', $name_arr);

        return view('post.edit', compact('post', 'tag_name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        if ($post->user_id != Auth::id()) {
            return redirect('post');
        }

        $update = Post::where('id', $id)
            ->update([
                "caption" => $request["caption"]
            ]);

        $tags_arr = explode(',', $request['tags']);
        $tag_ids = [];
        foreach ($tags_arr as $tag_name) {
            $tag = Tag::firstOrCreate([
                'tag_name' => $tag_name
            ]);
            $tag_ids[] = $tag->id;
        }
        $post->tags()->sync($tag_ids);

        return redirect('post');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        if ($post->user_id != Auth::id()) {
            return redirect('post');
        }

        Post::destroy($id);

        return redirect('post');
    }
}

resources/views/post/create.blade.php
@extends('layouts.home')

@section('content')
    <section class="card" style="background: #e8519e;">
        <div class="card-header">
            <h3 class="card-title">What is on your mind?</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="/post" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <textarea rows = "7" class="form-control" id="content" name="content" placeholder="What's happening?"></textarea>
                </div>
                <div class="form-group">
                    <label for="tags">Hashtag</label>
                    <input type="text" class="form-control" id="tags" name="tags" placeholder="Use comma to seperate each word">
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <span class=" float-right">Add image to your post
                    <input type="file" class="btn btn-light" name="image"></input>
                    <button type="submit" class="btn btn-light">Tweet</button>
                </span>
            </div>
        </form>
    </section>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.home')

@section('content')
<section class="content-header mt-5">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6 text-light">
                <h1>Edit Post</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/post" class="text-light">Post</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="card card-widget" style="background: #97caef; margin-top: 10px;">
        <div class="card-header">
            <h3 class="card-title">Edit Post</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="/post/{{ $post->id }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <img class="img-fluid pad mb-3" src="{{ asset('uploads/post/' . $post -> img_url) }}" alt="">
                <div class="form-group">
                    <label for="capton">Image Caption</label>
                    <textarea rows="10" class="form-control" id="caption"
                        name="caption">{{ old('caption', $post->caption) }}</textarea>
                </div>
                <div class="form-group">
                    <label for="tags">Hashtag</label>
                    <input type="text" class="form-control" id="tags" name="tags" value="{{old('tag_name', $tag_name)}}"
                        placeholder="Use comma to seperate each word">
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer float-right">
                <button type="submit" class="btn btn-light">Edit</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/post/index.blade.php
@extends('layouts.home')

@section('content')

<section class="content">
  <div class="row mr-0 pl-3">
    <!-- Main content -->
    <div class="col-md-8 mt-5 pt-4">
      @include('layouts.partials.post_modal')
      <div class="container-fluid">
        <button type="button" class="btn btn-block btn-light mb-4" data-toggle="modal"
          data-target="#exampleModalCenter">
          <i class="fas fa-plus-circle"></i>
          New Post
        </button>
        <!-- <a class="btn btn-block btn-light mb-4" href="{{ route('post.create') }}">Tweet</a> -->
        @forelse($posts as $key => $post)
        <!-- Box Comment -->
        <div class="card card-widget">
          <div class="card-header" style="background: #97caef;">
            <div class="user-block">
              @if ($post->user->profile->img_url === null)
              <img class="img-circle" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
              @else
              <img class="img-circle" src="{{ asset('uploads/profile/' . $post->user->profile -> img_url) }}"
                alt="User Image">
              @endif
              <span class="username"><a href="#" class="text-dark">{{ $post -> user -> username }}</a></span>
              <span class="description text-dark">{{ $post -> created_at }}</span>
            </div>
            <div class="card-tools">
              <div class="btn-group">
                <button type="button" class="btn btn-tool dropdown-toggle text-dark" data-toggle="dropdown">
                  <i class="fas fa-wrench"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" role="menu">
                  <a href="{{ route('post.show', ['post' => $post->id]) }}" class="dropdown-item">See</a>
                  @if ($post->isCreatedBySelf())
                  <a href="{{ route('post.edit', ['post' => $post->id]) }}" class="dropdown-item">Edit</a>
                  <form action="{{ route('post.show', ['post' => $post->id]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="Delete" class="dropdown-item btn btn-light btn-sm">
                  </form>
                  @endif
                </div>
              </div>
            </div>
            <!-- /.user-block -->
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <img class="img-fluid pad mb-3" src="{{ asset('uploads/post/' . $post -> img_url) }}" alt="">
            <?php $content = explode("\n", $post->caption);?>
            <ul>
              <?php
                for ( $i = 0; $i < count( $content ); $i++ ) {
                ?><li>{{ $content[$i] }}</li><?php
                }
              ?>
            </ul>
            <div>
              <p class="text-dark mt-2">Hashtag:</p>
              @forelse($post->tags as $tag)
              <button class="btn btn-light btn-sm">{{ $tag->tag_name }}</button>
              @empty
              No Hashtag
              @endforelse
            </div>
            <div class="mt-3">
              <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
              @if ($post->isLiked())
              <form class="d-inline" action="{{ route('post_like.destroy', ['post_like' => $post->id]) }}"
                method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Liked</button>
              </form>
              @else
              <form class="d-inline" action="{{ route('post_like.store') }}" method="POST">
                @csrf
                <input type="hidden" value="{{ $post->id }}" name="post_id" class="dropdown-item btn btn-light btn-sm">
                <button type="submit" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
              </form>
              @endif
              <span class="ml-2 text-muted">{{$post->likes->count()}} likes</span>
              <span class="float-right text-muted">{{$post->comments->count()}} comments</span>
            </div>
          </div>
          <!-- /.card-body -->
          <div class="card-footer card-comments">
            @foreach($post -> comments as $comment)
            <div class="card-comment">
              <!-- User image -->
              @if ($post->user->profile->img_url === null)
              <img class="img-circle img-sm" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
              @else
              <img class="img-circle img-sm" src="{{ asset('uploads/profile/' . $post->user->profile -> img_url) }}"
                alt="User Image">
              @endif
              <div class="comment-text text-dark">
                <span class="username">
                  {{ $comment -> user -> name }}
                  <div class="float-right d-flex flex-column align-items-end">
                    <span class="text-muted">{{ $comment -> created_at }}</span>
                    <div>
                      <span class="text-muted mr-2">{{ $comment->likes->count() }} likes</span>
                      @if ($comment->isLiked())
                      <form class="d-inline"
                        action="{{ route('comment_like.destroy', ['comment_like' => $comment->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i>
                          Liked</button>
                      </form>
                      @else
                      <form class="d-inline" action="{{ route('comment_like.store') }}" method="POST">
                        @csrf
                        <input type="hidden" value="{{ $comment->id }}" name="post_id"
                          class="dropdown-item btn btn-light btn-sm">
                        <button type="submit" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i>
                          Like</button>
                      </form>
                      @endif
                    </div>
                  </div>
                </span><!-- /.username -->
                {{ $comment -> content }}
              </div>
              <!-- /.comment-text -->
            </div>
            <!-- /.card-comment -->
            @endforeach
          </div>
          <!-- /.card-footer -->
          <div class="card-footer">
            <form action="/comment/{{ $post->id }}" method="POST">
              @csrf
              <!-- User image -->
              @if (Auth::user()->profile->img_url === null)
              <img class="img-fluid img-circle img-sm" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
              @else
              <img class="img-fluid img-circle img-sm" src="{{ asset('uploads/profile/' . Auth::user()->profile -> img_url) }}"
                alt="User Image">
              @endif
              <!-- .img-push is used to add margin to elements next to floating images -->
              <div class="img-push d-flex">
                <input type="text" class="form-control form-control-sm" name="content"
                  placeholder="Press enter to post comment">
                <input type="submit" value="Comment" class="btn btn-outline-dark btn-sm btn-light">
              </div>
            </form>
          </div>
          <!-- /.card-footer -->
        </div>
        <!-- /.card -->
        @empty
        <div class="text-center">No Post</div>
        @endforelse
      </div>
    </div>

    <!-- /.content -->
    <!-- Right sidebar -->
    @include('layouts.partials.right_sidebar', ['tags' => $tags, 'users' => $users])
    <!--/. Right sidebar -->
  </div>


</section>
@endsection

resources/views/post/show.blade.php
@extends('layouts.home')

@section('content')
<section class="content-header mt-5">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6 text-light">
        <h1>Post Detail</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/post" class="text-light">Post</a></li>
          <li class="breadcrumb-item active">Detail</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<section class="content">
  <!-- Box Comment -->
  <div class="card card-widget">
    <div class="card-header" style="background: #97caef;">
      <div class="user-block">
        <img class="img-circle" src="{{ url('https://randomuser.me/api/portraits/thumb/men/14.jpg') }}" alt="User Image">
        <span class="username"><a href="#" class="text-dark">{{ $post -> user -> username }}</a></span>
        <span class="description text-dark">{{ $post -> created_at }}</span>
      </div>
      <div class="card-tools">
        <div class="btn-group">
          <button type="button" class="btn btn-tool dropdown-toggle text-dark" data-toggle="dropdown">
            <i class="fas fa-wrench"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right" role="menu">
            <a href="{{ route('post.edit', ['post' => $post->id]) }}" class="dropdown-item">Edit</a>
            <form action="{{ route('post.show', ['post' => $post->id]) }}" method="POST">
              @csrf
              @method('DELETE')
              <input type="submit" value="Delete" class="dropdown-item btn btn-light btn-sm">
            </form>
          </div>
        </div>
      </div>
      <!-- /.user-block -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <img class="img-fluid pad mb-3" src="{{ asset('uploads/post/' . $post -> img_url) }}" alt="">
      <?php $caption = explode("\n", $post->caption);?>
      <ul>
        <?php
          for ( $i = 0; $i < count( $caption ); $i++ ) {
          ?><li>{{ $caption[$i] }}</li><?php
          }
        ?>
      </ul>
      <div>
        <p class="text-dark mt-2">Hashtag:</p>
        @forelse ($post->tags as $tag)
        <button class="btn btn-light btn-sm">{{ $tag->tag_name }}</button>
        @empty
        No Hashtag
        @endforelse
      </div>

      <div class="mt-3">
        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
        <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
        <span class="float-right text-muted">{{$post->comments->count()}} comments</span>
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer card-comments">
      @foreach($post -> comments as $comment)
      <div class="card-comment">
        <!-- User image -->
        <img class="img-circle img-sm" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
        <div class="comment-text text-dark">
          <span class="username">
            {{ $comment -> user -> name }}
            <span class="text-muted float-right">{{ $comment -> created_at }}</span>
          </span><!-- /.username -->
          {{ $comment -> content }}
        </div>
        <!-- /.comment-text -->
      </div>
      <!-- /.card-comment -->
      @endforeach
    </div>
    <!-- /.card-footer -->

    <div class="card-footer">
      <form action="/comment/{{ $post->id }}" method="post">
        @csrf
        <img class="img-fluid img-circle img-sm" src="{{ url('https://randomuser.me/api/portraits/thumb/men/14.jpg') }}" alt="Alt Text">
        <!-- .img-push is used to add margin to elements next to floating images -->
        <div class="img-push d-flex">
          <input type="text" class="form-control form-control-sm" name="content"
            placeholder="Press enter to post comment">
          <input type="submit" value="Comment" class="btn btn-outline-dark btn-sm btn-light">
        </div>

      </form>
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->
</section>

@endsection