routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    'post' => 'PostController',
]);

Route::resources([
    'follow' => 'FollowController',
]);

Route::resources([
    'profile' => 'ProfileController',
]);

Route::middleware('auth', 'throttle:60,1')->group(function () {
    Route::resource('post_like', 'PostLikeController', ['only' => ['destroy', 'store']]);
    Route::resource('comment_like', 'CommentLikeController', ['only' => ['destroy', 'store']]);
});

Route::post('/comment/{post_id}', 'CommentController@store');
//Route::get('/{user_id}', 'ProfileController@profile');

resources/views/layouts/partials/left_sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background: #123c69;">
  <!-- Brand Logo -->
  <a href="#" class="brand-link">
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Google_Camera_Icon.svg/1024px-Google_Camera_Icon.svg.png"
      class="brand-image mt-1 ml-4 mr-3" style="opacity: .8">
    <span class="brand-text font-weight-bold">InstaPhotos</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item menu-open">
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{ route('home') }}" class="nav-link font-weight-bold">
                <i class="fas fa-home nav-icon"></i>
                <p class="font-weight-bold text-light">Home</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('post.index') }}" class="nav-link font-weight-bold">
                <i class="fas fa-hashtag nav-icon"></i>
                <p class="font-weight-bold text-light">Explore</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link font-weight-bold">
                <i class="fas fa-bell nav-icon"></i>
                <p class="font-weight-bold text-light">Notifications</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link font-weight-bold">
                <i class="fas fa-envelope nav-icon"></i>
                <p class="font-weight-bold text-light">Messages</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link font-weight-bold">
                <i class="fas fa-bookmark nav-icon"></i>
                <p class="font-weight-bold text-light">Bookmarks</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link font-weight-bold">
                <i class="fas fa-list-alt nav-icon"></i>
                <p class="font-weight-bold text-light">Lists</p>
              </a>
            </li>
          </ul>
        </li>
        <!--
          <a href="{{ route('post.create') }}" class="btn btn-light btn-block btn-lg text-dark mt-4" style="border-radius:50px">
            Tweet
          </a> -->
        <button type="button" class="btn btn-light btn-block btn-lg text-dark mt-4" style="border-radius:50px"
          data-toggle="modal" data-target="#exampleModalCenter">
          <i class="fas fa-plus-circle"></i>
          New Post
        </button>
  </div>
  </ul>
  </nav>
  <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

resources/views/layouts/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-dark fixed-top" style="background: #4056a1;">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle font-weight-bold text-light" href="#" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                <!-- User image -->
                @if (Auth::user()->profile->img_url === null)
                <img width="30" height="30" class="d-inline-block align-top" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
                @else
                <img width="30" height="30" class="d-inline-block align-top" src="{{ asset('uploads/profile/' . Auth::user()->profile -> img_url) }}"
                  alt="User Image">
                @endif
                {{ Auth::user()->username }}
            </a>

            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a href="{{ route('profile.show', Auth::id()) }}" class="dropdown-item font-weight-bold text-dark">
                    <i class="fas fa-user-circle"></i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item font-weight-bold text-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                                 document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i>
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/partials/post_modal.blade.php
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="background: #97caef;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">New Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="/post" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="modal-body">
          <div class="form-group">
            <label for="img_url">Add image</label>
            <input type="file" class="btn btn-light" name="img_url"></input>
          </div>
          <div class="form-group">
            <label for="capton">Image Caption</label>
            <textarea rows="7" class="form-control" id="caption" name="caption"
              placeholder="What's happening?"></textarea>
          </div>
          <div class="form-group">
            <label for="tags">Hashtag</label>
            <input type="text" class="form-control" id="tags" name="tags" placeholder="Use comma to seperate each word">
          </div>
        </div>
        <div class="modal-footer">
          <div class="form-group">
            <button type="submit" class="btn btn-light float-right">Post</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/layouts/partials/right_sidebar.blade.php
<div class="col-md-4  mt-5 pt-4 pr-0">

  <div class="card rounded" style="background: #97caef;  position: -webkit-sticky; position: sticky; top: 60px;">
    <div class="card-header">
      <h3 class="card-title">Trends for you</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <ul class="products-list product-list-in-card pr-2">

        @forelse($tags as $tag)
        <li class="item pl-4 py-1" style="background: #97caef;">
          <a href="#" class="product-title text-dark"> {{ $tag->tag_name }}</a>
          <p>{{$tag->tagged_post_count()}} Posts</p>
        </li>
        @empty
        <p style="text-align:center">No Hashtag</p>
        @endforelse

      </ul>
    </div>
    <!-- /.card-body -->
  </div>

  <div class="card" style="background: #97caef;  position: -webkit-sticky; position: sticky; top: 290px;">
    <div class="card-header">
      <h3 class="card-title">Who to follow</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <ul class="products-list product-list-in-card pl-3 pr-2">

        @forelse($users as $key => $user)
        <li class="item" style="background: #97caef;">
          <div class="product-img">
            @if ($user->profile->img_url === null)
            <img class="img-circle img-size-50" src="{{ asset('images/profile-image.jpg') }}" alt="User Image">
            @else
            <img class="img-circle img-size-50" src="{{ asset('uploads/profile/' . $user->profile -> img_url) }}"
              alt="User Image">
            @endif

          </div>
          <div class="product-info">
            <a href="{{ route('profile.show', ['profile' => $user->profile->id]) }}"
              class="product-title text-dark">{{ $user->profile->full_name }}</a>
            <span>
              @if ($user->isFollowed())
              <form class="d-inline" action="{{ route('follow.destroy', ['follow' => $user->id]) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-light btn-sm float-right mt-2 mr-3 py-2"
                  style="border-radius:50px"> Unfollow</button>
              </form>
              @else
              <form class="d-inline" action="{{ route('follow.store') }}" method="POST">
                @csrf
                <input type="hidden" value="{{ $user->id }}" name="user_id" class="dropdown-item btn btn-light btn-sm">
                <button type="submit" class="btn btn-light btn-sm float-right mt-2 mr-3 py-2"
                  style="border-radius:50px">Follow</button>
              </form>
              @endif
            </span>
            <p>{{ $user->username }}</p>
          </div>
        </li>
        @empty
        No Recommendations
        @endforelse

      </ul>
    </div>
  </div>

  <div class="description mb-3" style="position: -webkit-sticky; position: sticky; top: 565px;">
    <p class="text-dark">Copyright &copy; 2020 Twitter All rights reserved.</p>
  </div>
</div>

resources/views/layouts/partials/tweet_modal.blade.php
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="background: #e8519e;">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Tweet</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="/post" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="modal-body">
              <div class="form-group">
                <textarea rows = "7" class="form-control" id="content" name="content" placeholder="What's happening?"></textarea>
              </div>
              <div class="form-group">
                <label for="tags">Hashtag</label>
                <input type="text" class="form-control" id="tags" name="tags" placeholder="Use comma to seperate each word">
              </div>
            </div>
            <div class="modal-footer">
              <span>Add image to your post
                <input type="file" class="btn btn-light" name="image"></input>
                <button type="submit" class="btn btn-light float-right">Tweet</button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>